#!/bin/bash

git submodule add -b gh-pages git@github.com:mongodb/mongo-java-driver 2> /dev/null
git submodule update --remote || exit

if [[ -z $1 || $# -gt 1 ]]; then
    echo "Usage: publish-docs <version>"
    exit 1
fi

version=$1
echo version: ${version}

# make the reference docs
cd reference || exit
rm -rf public
hugo

mkdir ../mongo-java-driver/${version}
rsync -a public/* ../mongo-java-driver/${version}
rm -rf public

cd ..

# make the landing page
cd landing || exit
rm -rf public
hugo

rsync -a public/* ../mongo-java-driver/
rm -rf public

cd ..

# publish the docs
# you will need push access to the mongo-java-driver repo's gh-pages branch
